# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ffc61c1e3cac9d6ba7ab79a4e11af0e076a55c3448ad10655212f41d44c404c27e674c7eaf9bacaff3dcf6bf784aa9bfa8d20fef6f734dc2327d08893ee5a37

test:
  secret_key_base: 14137b64a6a9e20b1d56d06851cab5b953c6cc8523afca8da6059c2853d37f9557ba25c6e02fb28c3daf56001710eecc16a2aab7818fa8f1c8840471006e0906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
