# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09ba88d7cbe68f425de59e69a9ec0ea53e2b17b352366e18edc7b1fb41f63e3cbc9e64050505f51fad97650ad166237b32684ba383749d2b9f4d1e12ab321bad

test:
  secret_key_base: 914913167317f803af44232ec5f9771ccc5d528a17da8dc875c6588fa24ba139c213bfb070fc71d6b0e7ab4240093c65c317b2fc7701f57eaaf3572d821b0d3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
